### ISSUE TITLE
.onion site support

### ISSUE THREAD

**Issue by distrair** [basil00/TorWall#46] opened 2022-03-15 13:18 UTC
Other apps like Tallow allows to connect to .onion websites, but other apps does not route all traffic that outcomes from my pc through tor, and tallow does not allow to connect to .onion websites. Is it Tallow problem or it just configuration?

**Comment by basil00** [comment] 2022-03-20 01:47
Closed as a duplicate of #14

**Closed as completed by basil00** 2022-03-20 01:47 UTC
